name: Knot
version: 1.2

api: 1.13.0

main: Knot\Main

load: STARTUP

author: shoghicp

website: "https://github.com/TheLucyClubMCPE/"

description: "Tie servers together with the amazing Knot!"

commands:

 transfer:

  permission: knot.command.server

  usage: "/server [player] <address> <port>"

permissions:

 fasttransfer.command.transfer:

  description: "Allows players to change servers"

  default: op
